# Site Settings
title: Jackson County Alabama Cattlemen's Association
description: Jackson County Alabama Cattlemen's Association News and Events
url: https://jackson-cattlemen.github.io/jacksoncattlemen.com

# Jekyll Configuration
encoding: UTF-8
permalink: /:title/
paginate: 5
paginate_path: "/news/page/:num/"

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass/SCSS settings
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Custom Collections
collections:
  events:
    output: true
    permalink: /events/:title/

# Collection Defaults
defaults:
- scope:
    type: posts
  values:
    layout: post
- scope:
    type: pages
  values:
    layout: page
- scope:
    type: events
  values:
    layout: page

# Frontmatter Defaults
sidebar_options:
  - sidebar
  - no-sidebar

# File Handling
include: [_pages]
exclude: [lib, config.rb, .sass-cache, Capfile, config, log, Rakefile, Rakefile.rb, tmp, Gemfile, Gemfile.lock, README.md, LICENSE.md, node_modules, gulpfile.js, package.json]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    categories: '/category/:name/'
    tags: '/tag/:name/'

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
